---
- name: Deploy Ansible development server using builtin modules only
  hosts: all
  become: true

  vars:
    # username for private automation hub for EE or to password protected registry
    registry_user: "USERNAME"
    # password for private automation hub for EE or to password protected registry
    registry_pass: "PASSWORD"
    # username for development server
    username: "ansible"
    # port for web server access
    dev_server_port: 443
    # folder to create to copy ssl certs from
    certandkeysourcefolder: "/certs/"
    # folder to create to deploy ssl certs to
    certandkeydestfolder: "/certs/"
    # name of certificate, delete if using self-signed
    cert_name: "CERT.cer"
    # name of key, delete if using self-signed
    key_name: "KEY.key"
    # specific image to pull to development server and assign in ansible-navigator.yml
    ansible_image: "registry.redhat.io/ansible-automation-platform-23/ee-supported-rhel8:latest"
    # Deploy an inventory, group variables and host variables files from files folder in role
    deploy_inventory: true
    # Deploy an example repository with a basic role structure
    deploy_example_repo: true

  roles:
    - shadowman_dev_server_builtin
