---
- name: Deploy Ansible development server using builtin modules only
  hosts: all
  become: true

  vars:
    # ############################################################################################
    # NOTE:  In Ansible Controller, use the credential "Private Automation Hub Credentials"
    # NOTE2: Variables in ALL CAPS come from the survey in Ansible Controller
    # ############################################################################################

    # username for private automation hub for EE or to password protected registry - "Automation Hub Credentials" credential type
    registry_user: "{{ lookup('env', 'AH_USERNAME') }}"  # "pah-ee-user"
    # password for private automation hub for EE or to password protected registry - "Automation Hub Credentials" credential type
    registry_pass: "{{ lookup('env', 'AH_PASSWORD') }}"

    # username for development server
    username: "{{ USER_NAME }}"
    # username for development server
    usergroup: "{{ USER_GROUP }}"
    # username for development server
    code_server_password: "{{ CODE_SERVER_PASSWORD }}"
    # Token used to interact with PAH to pull collections
    pah_token: "{{ PAH_TOKEN }}"
    # port for web server access - accessable port range: 8000-8050
    dev_server_port: "{{ PORT| default('') }}"
    # user prompt to ensure port is available via /app/code-server/ports-assigned.txt
    # port_available_validate: false # "{{ PORT_AVAILABLE_VALIDATE | default('false') | bool }}"

    # server to deploy code-server
    dev_hostname: "{{ DEV_HOSTNAME }}"


    # specific image to pull to development server and assign in ansible-navigator.yml
    ansible_image: "a70lpisyanst009.mgmt.bcbssc.com/ansible-automation-platform-24/ee-supported-rhel8:latest"

    # Deploy an inventory, group variables and host variables files from files folder in role
    deploy_inventory: "{{ DEPLOY_INVENTORY | default('false') | bool }}"
    # Deploy an example repository with a basic role structure
    deploy_ansiblegalaxy_repo: "{{ DEPLOY_EXAMPLE_REPO | default('false') | bool }}"

    # #######################################################
    # Certificate information
    # #######################################################
    # folder to copy ssl certs from (built into EE or mounted at runtime) or localhost folder if running ansible-playbook
    # certandkeysourcefolder: "/certs/"
    certandkeysourcefolder: "/etc/tower/"

    # folder to create to deploy ssl certs to
    certandkeydestfolder: "/etc/pki/tls/certs/"

    # name of certificate, delete if using self-signed
    cert_name: "tower.cert"  # "CERT.cer"

    # name of key, delete if using self-signed
    key_name: "tower.key"  # "KEY.key"


  # List of roles to run limited to server identified in Ansible Controller survey
  roles:
    - role: dev_server_builtin
      # when: inventory_hostname == "{{ DEV_HOSTNAME }}"
