---
- name: Deploy vscode extensions
  hosts: a70lpisyanst008.mgmt.bcbssc.com  # all
  become: true

  vars:
    # username for development server
    username: "{{ USER_NAME }}"  

    # specific image to pull to development server and assign in ansible-navigator.yml
    ansible_image: "a70lpisyanst009.mgmt.bcbssc.com/ansible-automation-platform-24/ee-supported-rhel8:latest"

  roles:
    - role: update_vscode_extension

