---
version: "4.17.0"
codeserver_url: https://github.com/coder/code-server/releases/download/v{{ version }}/code-server-{{ version }}-amd64.rpm
deploy_inventory: true
deploy_example_repo: true
deploy_ansiblegalaxy_repo: false
