---
- name: Update Node version for Code-Server
  hosts:
    - a70lqisyanst004.mgmt.bcbssc.com
    - a70lpisyanst004.mgmt.bcbssc.com
    - a70lpisyanst008.mgmt.bcbssc.com
  become: true

  # tags:
  #   - download_cs

  vars:
    node_version: "18.18.2"

  tasks:
    - name: Replace old Node version with approved Node version
      ansible.builtin.copy:
        src: /app/code-server/node-v{{ node_version }}-linux-x64/bin/node
        dest: /usr/lib/code-server/lib/node
        mode: 'preserve'
        force: true
        remote_src: true

    - name: Insert line for Strict-Transport-Security
      ansible.builtin.lineinfile:
        path: /usr/lib/code-server/out/node/routes/index.js
        insertafter: '^(\s*)app\.router\.use\(\(req, res, next\) => __awaiter\(void 0, void 0, void 0, function\* \(\) \{' # line 109
        line: "        res.setHeader('Strict-Transport-Security', 'max-age=31536000; includeSubDomains; preload');"

    - name: Gather all services
      ansible.builtin.service_facts:

    - name: Restart all running code-server services
      ansible.builtin.systemd:
        name: "{{ item.value.name }}"
        state: restarted
        daemon_reload: true
      when:
        - '"code-server" in item.value.name'
        - item.value.state == "running"
      loop: "{{ ansible_facts.services | dict2items }}"
